# Generated by Django 6.0.4 on 2026-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
